apiVersion: v1
kind: Secret
metadata:
  name: workshop-api-secrets
  namespace: workshop
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/workshop_db
  JWT_SECRET: secretKey
  JWT_REFRESH_SECRET: refreshSecretKey
