apiVersion: v1
kind: Secret
metadata:
  name: auto-repair-shop-api-secrets
  namespace: oficina
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/auto_repair_shop
  JWT_SECRET: secretKey
  JWT_REFRESH_SECRET: refreshSecretKey
