apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-repair-shop-api
  namespace: oficina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-repair-shop-api
  template:
    metadata:
      labels:
        app: auto-repair-shop-api
    spec:
      containers:
        - name: auto-repair-shop-api
          image: 051826705770.dkr.ecr.us-east-1.amazonaws.com/auto-repair-shop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          env:
            # Variáveis do ConfigMap
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: auto-repair-shop-api-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auto-repair-shop-api-config
                  key: PORT

            # Variáveis do Secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auto-repair-shop-api-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auto-repair-shop-api-secrets
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: auto-repair-shop-api-secrets
                  key: JWT_REFRESH_SECRET
      imagePullSecrets:
        - name: ecr-registry
