apiVersion: v1
kind: Service
metadata:
  name: auto-repair-shop-api
  namespace: oficina
spec:
  type: NodePort
  selector:
    app: auto-repair-shop-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
