apiVersion: v1
kind: Service
metadata:
  name: workshop-api
  namespace: workshop
spec:
  type: ClusterIP
  selector:
    app: workshop-api
  ports:
    - port: 3000
      targetPort: 3000
      name: http
