apiVersion: v1
kind: Service
metadata:
  name: workshop-api
  namespace: workshop
spec:
  type: NodePort
  selector:
    app: workshop-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
