apiVersion: v1
kind: Service
metadata:
  name: auto-repair-shop-api
  namespace: oficina
spec:
  type: LoadBalancer
  selector:
    app: auto-repair-shop-api
  ports:
    - port: 80
      targetPort: 3000
