apiVersion: v1
kind: Service
metadata:
  name: auto-repair-shop-api
  namespace: oficina
spec:
  type: ClusterIP
  selector:
    app: auto-repair-shop-api
  ports:
    - port: 3000
      targetPort: 3000
      name: http
