name: Provision EKS via Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2Ô∏è‚É£ Configure AWS credentials (usar a role criada pelo Terraform)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      # 3Ô∏è‚É£ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 4Ô∏è‚É£ Terraform Init
      - name: Terraform Init
        run: terraform -chdir=terraform init -backend-config=dev.aws.tfbackend -input=false

      # 5Ô∏è‚É£ Terraform Validate
      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      # 6Ô∏è‚É£ Terraform Plan (read-only)
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan -input=false -var-file="dev.tfvars"

      # 7Ô∏è‚É£ Terraform Apply (full access)
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve -input=false tfplan

      # 8Ô∏è‚É£ Configure kubectl
      - name: Configure kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name workshop-cluster

      # 9Ô∏è‚É£ Apply ClusterIP Service
      - name: Apply ClusterIP Service
        run: kubectl apply -f k8s/service-api-cluster-ip.yml -n workshop

      # üîü Show Terraform Outputs
      - name: Terraform Outputs
        run: terraform -chdir=terraform output
