name: Terraform EKS

on:
  push:
    branches:
      - main
  workflow_dispatch: # permite rodar manualmente (para destroy)

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Pegar o c√≥digo
      - name: Checkout
        uses: actions/checkout@v3

      # 2Ô∏è‚É£ Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3Ô∏è‚É£ Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 4Ô∏è‚É£ Inicializar Terraform
      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      # 5Ô∏è‚É£ Decidir entre apply ou destroy
      - name: Terraform Plan/Apply or Destroy
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "üö® Destroy acionado manualmente"
            terraform -chdir=terraform destroy -auto-approve -input=false
          else
            echo "‚úÖ Plan e Apply no push"
            terraform -chdir=terraform plan -out=tfplan -input=false
            terraform -chdir=terraform apply -auto-approve tfplan
          fi
